### ISSUE TITLE
failed to activate : Symbol’s function definition is void: company-ph--quickhelp

### ISSUE THREAD

**Issue by hogren** [vpxyz/php-quickhelp#3]
Hello,

Since a quiet long time I use company-php.  It works with this (minimized) configuration : 

     (require 'package)
     (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
     (package-initialize)
     (add-hook 'php-mode-hook
     	  (lambda ()
     
     	    (set (make-local-variable 'company-backends)
                     '(company-ac-php-backend company-web-html company-dabbrev-code company-files))
    	    (setq company-idle-delay 0)
    	     (company-mode))
     	  )

With that, I have a popup when I begin to enter "preg_" for example.

I tried to activate company-quickhelp-mode (via .emacs or dynamically). Ok, I have the first popup, and after 1 sec of each move in the popup, I have a little "tooltip" with a very little more infos. 

Now I try to activate your php-quickhelp. Following the README, I change the config like this : 

    (require 'package)
    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
    (package-initialize)
    (add-hook 'php-mode-hook
    	  (lambda ()
    	    (require 'php-quickhelp)
    	    (set (make-local-variable 'company-backends)
                     '(company-ph--quickhelp company-web-html company-dabbrev-code company-files))
    	    (setq company-idle-delay 0)
    	     (company-mode))
    	  )

When I restart Emacs and enter in a PHP file, I have this error :
```
Company backend ’company-ph--quickhelp’ could not be initialized:
Symbol’s function definition is void: company-ph--quickhelp
```

I tested to use "php-quickhelp-company-php" in place of "company-ph--quickhelp". I have a quiet different error : 
```
Company backend ’php-quickhelp-company-php’ could not be initialized:
Symbol’s function definition is void: company-php
```

Do you have any idea about this problem ?

Thanks !

**Comment by vpxyz** [comment]
Thank you! I have just fixed the issue. 
As soon as possible I try to figure out how, if php-quickhelp doesn't find the documentation, to reuse the one provided by company-php.

**Comment by hogren** [comment]
Hello, Thanks for your reactivity.
Now, I have no error message when I use `'(php-quickhelp-company-php company-web-html company-dabbrev-code company-files))` **but the help is always not shown**.
Did I miss anything ?

Thanks !

**Comment by vpxyz** [comment]
Ciao!
You may have forgotten to put  `(require 'company-php)` ?
I'm using this hook to test and fix the issue: 
`
(add-hook 'php-mode-hook
(lambda ()
            (require 'company-php)
            (require 'php-quickhelp)
            (set (make-local-variable 'company-backends)
                     '(php-quickhelp-company-php company-web-html company-dabbrev-code company-files))
            (setq company-idle-delay 0)
             (company-mode))
          )
`
I guess you had  installed  [jq](https://stedolan.github.io/jq/)  and called `php-quickhelp-download-or-update` after the installation of php-quickhelp.
Please could you show me the messages that appear in `*Messages*`?
Thanks

**Comment by hogren** [comment]
Hello,

I tried with your hook. I have the same result.

This is my *Message* buffer :

    Loading 00debian-vars...done
    Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
    Loading debian-ispell...done
    Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...done
    For information about GNU Emacs and the GNU system, type C-h C-a.
    Function provided is already compiled
    Eager macro-expansion failure: (wrong-number-of-arguments (2 . 2) 10)

The Eager message is only on one of my two machines.

I good downloaded the php doc :

    $ ls ~/.emacs.d/
    auto-save-list  %backup%~  elpa  php-quickhelp-manual
    $ ls -lh ~/.emacs.d/php-quickhelp-manual/
    total 3.3M
    -rw------- 1 adauvray adauvray 3.3M Jul 23 15:38 php_manual_en.json

I have jq : 

    $ whereis jq
    jq: /usr/bin/jq /usr/share/man/man1/jq.1.gz

Thanks @vpxyz for help.

**Comment by vpxyz** [comment]
That's pretty weird.
What version of emacs are you using? 
What versions of company-php and php-quickhelp do you have installed? I will try to replicate this bug.

**Comment by hogren** [comment]
The value of variable package-activated-list is
(company-php ac-php-core company-quickhelp company-web company f dash php-mode php-quickhelp popup pos-tip s web-completion-data xcscope)

The value of emacs-version is 25.2.2

The version of company-php is 20201009.1025 and the version of php-quickhelp is 20210721.1945.

This machine is on Ubuntu 18.04.

Thank you again @vpxyz .

**Comment by hogren** [comment]
I am trying de debug. I found that there is a problem inside the cl-case of php-quickhelp-company-php function. The last condition is always executed. The php-quickhelp--function is never called.

**Comment by hogren** [comment]
@vpxyz And the function php-quickhelp-at-point seems to work. When I place the cursor after "preg_replace" and call the function. The frame is divided in two parts with the help written in the second. So JQ execution is ok. The documentation is good downloaded, etc.

**Comment by vpxyz** [comment]
Ok, I had just fixed the incompatibility with emacs 25 (setq-local in the old version of emacs can be used only with one variable and one value). 
I have tested on a ubuntu 18.04 with emacs 25.2 with this configuration (with company-quickhelp and company-quickhelp-terminal if you want to use in console):
`
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '
(package-selected-packages
   (quote
    (company-quickhelp-terminal web-mode company-web php-quickhelp company-php company)))
 '(show-paren-mode t)
 '(company-quickhelp-mode t)
 '(company-quickhelp-terminal-mode t)
 )
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )


(add-hook 'php-mode-hook (lambda ()
			   ;; .... other configs
			   (require 'company-php)
			   (require 'php-quickhelp)
			   (set (make-local-variable 'company-backends)
			   	'(php-quickhelp-company-php company-web-html company-dabbrev-code company-files))
			   (company-mode)))
`
and it seems to work. 
![emacs-25_quickhelp](https://user-images.githubusercontent.com/9392182/126902934-c21433aa-8ce2-4cd4-9d2d-cf7f02321ac2.png)

Thank you!

**Comment by hogren** [comment]
Ohh really good !!
With your correction AND your config, I success to use php-quickhelp. 

An enormous thank to you for your work ! It’s really appreciate.

**Comment by hogren** [comment]
@vpxyz Hello, sorry it’s me again. After a couple of day, Php-quickhelp is broken. I don’t know what I did.
I delete my .emacs.d/elpa directory. I empty my .emacs, and paste your config. I run package-install-selected-packages.

When I try to work with a php file, Company is ok, but at the time to show the help, I have this message : 
Error running timer ‘company-quickhelp--show’: (error "Company: backend php-quickhelp-company-php error \"Wrong type argument: char-or-string-p, nil\" with args (doc-buffer str_replace()")

Any idea ?

Thank you very much !!

**Comment by vpxyz** [comment]
Ciao,
I think you need to run `php-quickhelp-download-or-update`.  That problem happens when `jq` doesn't find the documentation file.
A more pleasant configuration to use may be this one:
```elisp
(add-hook 'php-mode-hook
          (lambda ()
            (require 'company-php)
            (require 'php-quickhelp)
            (set (make-local-variable 'company-backends)
                     '(php-quickhelp-company-php company-web-html company-dabbrev-code company-files))
            (setq company-idle-delay 0)
            (ac-php-core-eldoc-setup)
            (define-key php-mode-map  (kbd "M-.") 'ac-php-find-symbol-at-point) ;goto definition
            (define-key php-mode-map  (kbd "M-,") 'ac-php-location-stack-back)  ;go back
            (company-mode t)))
```

Bye!

**Comment by hogren** [comment]
Hello, I downloaded again the doc. I enter your config in my .emacs.
The help is not shown.
In *Messages*, I have "php-quickhelp--html2fontify-string: Wrong type argument: char-or-string-p, nil".

Do you know why ?

Thanks !

**Comment by hogren** [comment]
After research, I reinstall company-quickhelp which was not installed automatically.

But I have again this message : 
Error running timer ‘company-quickhelp--show’: (error "Company: backend php-quickhelp-company-php error "Wrong type argument: char-or-string-p, nil" with args (doc-buffer str_replace()")

**Comment by vpxyz** [comment]
Sorry, I am not able to replicate the problem.
I deleted .emacs.d/elpa (in my virtual machine) and reinstalled the packages by running `package-install-selected-packages`. In elpa I now have these packages: 
```
drwxrwxr-x 17 vagrant vagrant 4096 Aug 12 21:23 .
  drwx------  7 vagrant vagrant 4096 Aug  9 20:12 ..
  drwxr-xr-x  2 vagrant vagrant 4096 Aug 12 21:23 ac-php-core-20210617.949
  drwxrwxr-x  4 vagrant vagrant 4096 Aug 12 21:22 archives
  drwxr-xr-x  3 vagrant vagrant 4096 Aug 12 21:23 company-20210811.214
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 company-php-20201009.1025
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 company-quickhelp-20210515.2212
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 company-quickhelp-terminal-20210715.1010
  drwxr-xr-x  2 vagrant vagrant 4096 Aug 12 21:23 dash-20210708.2009
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 f-20210624.1103
  drwx------  3 vagrant vagrant 4096 Aug 12 21:26 gnupg
  drwxr-xr-x  2 vagrant vagrant 4096 Aug 12 21:23 php-mode-20210808.1745
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 php-quickhelp-20210725.1413
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 popup-20210625.400
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 pos-tip-20191227.1356
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 s-20210616.619
  drwxrwxr-x  2 vagrant vagrant 4096 Aug 12 21:23 xcscope-20210719.828
```
Then I ran `php-quickhelp-download-or-update`, and it works as usual.

**Comment by hogren** [comment]
@vpxyz  It’s really strange. I have my Ubuntu machine on which it works. I copied .emacs and .emacs.d (delete and replace) on my Windows machine. I removed .elc files. I tested with emacs 25.3 and 27.2 . I have the same problem !

jq is in my PATH. 

So I don’t understand.

Any Idea ?

Thank you !

**Comment by hogren** [comment]
@vpxyz  ! I found an interesting thing !

I extract a generated jq command : 
.../jq.exe  -j -M '.["str_replace"] | "\(.purpose)###\(.return)###(\(.versions))"' .../.emacs.d/php-quickhelp-manual/php_manual_en.json

This command does not work because the jq filter is surrounded by a right single quote (U+2019) and not an apostrophe (U+0027).

It’s maybe related to my use of Bepo keymap, or it’s maybe just that Windows does not accept this character to surround an command argument.

Do you think that you can modify that ?

Thank you !!

**Comment by hogren** [comment]
@vpxyz I successed to repair. I change the line 188. (I made a PR)

**Comment by vpxyz** [comment]
Thank you. I just pushed a new version with your patch (and another for eldoc). I'm sorry I'm on a mountain vacation with limited connection.

**Comment by hogren** [comment]
Great ! Thank you and good holidays !
